//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/PlayerMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerMovement : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerMovement"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""079fc3c8-2838-46a4-851a-ac95e234b32d"",
            ""actions"": [
                {
                    ""name"": ""Invert Gravity"",
                    ""type"": ""Button"",
                    ""id"": ""a9c492a0-43f8-4922-8740-34ad99067960"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left and Right"",
                    ""type"": ""Button"",
                    ""id"": ""56fdb2ca-9248-4ab6-b483-e092c883289a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4c1031b9-d7cc-415b-8c5d-f588de0d491b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Invert Gravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ce9251f2-0bfc-4941-ba57-15b8942a9c87"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left and Right"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0242ca30-3cd9-4111-8873-d634ebbe00fc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left and Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ed707dec-e9df-427b-a853-7b4a5843f7ca"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left and Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_InvertGravity = m_Movement.FindAction("Invert Gravity", throwIfNotFound: true);
        m_Movement_LeftandRight = m_Movement.FindAction("Left and Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private IMovementActions m_MovementActionsCallbackInterface;
    private readonly InputAction m_Movement_InvertGravity;
    private readonly InputAction m_Movement_LeftandRight;
    public struct MovementActions
    {
        private @PlayerMovement m_Wrapper;
        public MovementActions(@PlayerMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @InvertGravity => m_Wrapper.m_Movement_InvertGravity;
        public InputAction @LeftandRight => m_Wrapper.m_Movement_LeftandRight;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void SetCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterface != null)
            {
                @InvertGravity.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnInvertGravity;
                @InvertGravity.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnInvertGravity;
                @InvertGravity.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnInvertGravity;
                @LeftandRight.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnLeftandRight;
                @LeftandRight.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnLeftandRight;
                @LeftandRight.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnLeftandRight;
            }
            m_Wrapper.m_MovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @InvertGravity.started += instance.OnInvertGravity;
                @InvertGravity.performed += instance.OnInvertGravity;
                @InvertGravity.canceled += instance.OnInvertGravity;
                @LeftandRight.started += instance.OnLeftandRight;
                @LeftandRight.performed += instance.OnLeftandRight;
                @LeftandRight.canceled += instance.OnLeftandRight;
            }
        }
    }
    public MovementActions @Movement => new MovementActions(this);
    public interface IMovementActions
    {
        void OnInvertGravity(InputAction.CallbackContext context);
        void OnLeftandRight(InputAction.CallbackContext context);
    }
}
